import {useEffect,useMemo,useState} from "react";
import {getContent,ingestContent} from "../api";
import {mockContent} from "../mocks/data";
import {Page,Card,State} from "../components/UI";
import type {ContentItem} from "../types";

export default function ContentLibrary(){
  const [items,setI]=useState<ContentItem[]>(mockContent),[loading,setL]=useState(false),[error,setE]=useState(""),[platform,setPlatform]=useState("All platforms"),[query,setQuery]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[performance,setPerformance]=useState("Any performance"),[uploading,setUploading]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{setL(true);getContent().then(setI).catch(()=>setE("Backend unavailable — showing seeded demo data.")).finally(()=>setL(false))},[]);
  const platforms=useMemo(()=>["All platforms",...new Set(items.map(x=>x.platform))],[items]);
  const visible=items.filter(x=>(platform==="All platforms"||x.platform===platform)&&(!from||x.date>=from)&&(!to||x.date<=to)&&(performance==="Any performance"||x.performance.toLowerCase().includes(performance.toLowerCase()))&&`${x.title} ${x.format} ${x.performance}`.toLowerCase().includes(query.toLowerCase()));
  const upload=async(file?:File)=>{if(!file)return;setUploading(true);setMessage("");setE("");try{const form=new FormData();form.append("file",file);await ingestContent(form);setMessage("Upload received. Refreshing content…");setI(await getContent())}catch{setE("Upload failed. Confirm the API server is running and accepts POST /content/ingest.")}finally{setUploading(false)}};
  return <Page title="Content Library"><State loading={loading} error={error}/><Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><input className="input" placeholder="Search title or format" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input" value={platform} onChange={e=>setPlatform(e.target.value)}>{platforms.map(x=><option key={x}>{x}</option>)}</select><select className="input" value={performance} onChange={e=>setPerformance(e.target.value)}><option>Any performance</option><option value="high">High</option><option value="low">Low</option></select><label className="text-xs text-slate-500">From<input className="input mt-1" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs text-slate-500">To<input className="input mt-1" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="btn btn-soft flex cursor-pointer items-center justify-center">{uploading?"Uploading…":"Ingest CSV"}<input className="sr-only" type="file" accept=".csv,text/csv" disabled={uploading} onChange={e=>void upload(e.target.files?.[0])}/></label></div>{message&&<p className="mt-3 text-sm text-emerald-700">{message}</p>}</Card><Card className="mt-4"><p className="mb-3 text-xs text-slate-500">Showing {visible.length} of {items.length} content items</p><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500">{["Title","Platform","Format","Date","Performance","Saves","Comments","Clicks"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(x=><tr className="border-b last:border-0" key={`${x.title}-${x.date}`}><td className="p-3 font-medium"><span>{x.title}</span>{x.synthetic&&<span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-amber-800">Sample</span>}</td><td className="p-3">{x.platform}</td><td className="p-3">{x.format}</td><td className="p-3">{x.date}</td><td className="p-3">{x.performance}</td><td className="p-3">{x.saves??"—"}</td><td className="p-3">{x.comments??"—"}</td><td className="p-3">{x.clicks??"—"}</td></tr>)}</tbody></table>{visible.length===0&&<p className="p-8 text-center text-sm text-slate-500">No matching content.</p>}</div></Card></Page>
}
