import {useEffect,useState} from "react";
import {isAxiosError} from "axios";
import {Link} from "react-router-dom";
import {getPlan,savePlan,generateContent} from "../api";
import {mockPlan} from "../mocks/data";
import {Page,Card} from "../components/UI";
import type {GeneratedContent,PlanItem} from "../types";

export default function Planner(){
  const [plan,setP]=useState<PlanItem[]>(mockPlan),[busy,setB]=useState<string>(""),[demo,setDemo]=useState(false),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[draft,setDraft]=useState<GeneratedContent|null>(null);
  useEffect(()=>{getPlan().then(p=>{setP(p);setDemo(false)}).catch(()=>setDemo(true))},[]);
  const generate=async(s:PlanItem)=>{setB(s.day);setMessage("");setDraft(null);try{const result=await generateContent(s);setDraft(result);setMessage(`Draft generated using Hindsight Reflect and ${result.memoriesUsed} directly relevant memories.`)}catch(error){const detail=isAxiosError(error)?(error.response?.data as {error?:{message?:string}}|undefined)?.error?.message:undefined;setMessage(detail??"Draft generation failed; the server did not return generated content.")}finally{setB("")}};
  const persist=async()=>{setSaving(true);setMessage("");try{const saved=await savePlan(plan);setP(saved);setDemo(false);setMessage("Weekly plan saved by the API.")}catch{setMessage("Plan was not saved. Connect POST /content/plan to persist it.")}finally{setSaving(false)}};
  return <Page title="Content Planner" action={<button className="btn btn-primary" onClick={()=>void persist()} disabled={saving || plan.length===0}>{saving?"Saving…":"Save weekly plan"}</button>}><p className="mb-4 text-sm text-slate-500">Weekly plan · select a slot to generate a draft grounded in Hindsight memories.</p>{demo&&<div className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Showing seeded sample plan because the API is unavailable.</div>}{message&&<div className="mb-4 rounded-xl bg-slate-100 p-3 text-sm text-slate-700" role="status">{message}</div>}{draft&&<Card className="mb-4 border-violet-200"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">Generated draft</h2><span className="text-xs text-violet-700">Hindsight Reflect · {draft.memoriesUsed} matching memories</span></div><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-6">{draft.content}</pre><div className="mt-4 border-t pt-3"><h3 className="text-sm font-semibold">Memory evidence</h3>{draft.relevantMemories.map((item,index)=><p className="mt-2 rounded-lg bg-violet-50 p-3 text-xs text-slate-600" key={`${index}-${item}`}>{item}</p>)}</div></Card>}{plan.length===0 ? <Card><p className="text-sm text-slate-600">No saved plan or memory-derived content ideas yet. Add brand and content memories first.</p></Card> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{plan.map(s=><Card className="flex min-h-64 flex-col" key={s.day}><p className="text-xs font-bold uppercase text-violet-600">{s.day}</p><h2 className="mt-3 font-semibold">{s.topic}</h2><p className="mt-2 text-sm text-slate-500">{s.format ?? "Format not available"} · {s.platform ?? "Platform not available"}</p><p className="mt-3 flex-1 text-xs leading-5 text-slate-600">{s.reasoning}</p><Link className="mt-3 text-xs font-medium text-violet-700 hover:underline" to="/strategist">View strategy rationale →</Link><button className="btn btn-soft mt-3 w-full" onClick={()=>void generate(s)} disabled={busy===s.day}>{busy===s.day?"Generating…":"Generate content"}</button></Card>)}</div>}</Page>
}
